# Generated by Django 5.2.4 on 2025-07-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_cards_is_expired_alter_cards_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='is_expired',
        ),
        migrations.AlterField(
            model_name='cards',
            name='expire',
            field=models.CharField(default='ACTIVE', help_text='Expiration date in MM/YY format (e.g., 12/25)', max_length=5),
        ),
    ]
