# Generated by Django 5.2.4 on 2025-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_remove_cards_is_expired_alter_cards_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='expire',
            field=models.CharField(help_text='Expiration date in MM/YY format (e.g., 12/25)', max_length=5),
        ),
    ]
