# Generated by Django 5.2.4 on 2025-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('code', models.IntegerField(help_text='Unique Integer Error code', primary_key=True, serialize=False, unique=True)),
                ('en', models.TextField(help_text='Error message in English')),
                ('uz', models.TextField(help_text='Error message in Uzbek')),
                ('ru', models.TextField(help_text='Error message in Russian')),
            ],
            options={
                'verbose_name': 'Error message',
                'verbose_name_plural': 'Error messages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(db_index=True, help_text='Unique external ID (generated by client)', max_length=255, unique=True)),
                ('sender_card_number', models.CharField(help_text='(Must exist in cards table)', max_length=16)),
                ('receiver_card_number', models.CharField(help_text='Must exist in cards table', max_length=16)),
                ('sender_card_expiry', models.CharField(help_text='(Expiry date, format check)', max_length=5)),
                ('sender_phone', models.CharField(blank=True, help_text='(Optional, used for logging/sending messages)', max_length=16, null=True)),
                ('receiver_phone', models.CharField(blank=True, help_text='(Optional, used for logging/sending messages)', max_length=16, null=True)),
                ('sending_amount', models.DecimalField(decimal_places=2, help_text='(Amount )', max_digits=10)),
                ('currency', models.CharField(choices=[('RUB', 'rub'), ('USD', 'usd'), ('UZS', 'uzs')], max_length=5)),
                ('receiving_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount receiver will get (auto-calculated)', max_digits=18)),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('try_count', models.SmallIntegerField(default=0, help_text='OTP attempt count (max 3)')),
                ('otp', models.CharField(blank=True, help_text='6-digit OTP code sent for confirmation', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
